export const ADMIN_HTML = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EPhone 反馈管理</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f6f4f9;color:#222;font:14px/1.5 -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif}header{height:60px;display:flex;align-items:center;padding:0 20px;background:#fff;border-bottom:1px solid #e8e4ec;font-size:18px;font-weight:700}main{display:grid;grid-template-columns:340px 1fr;min-height:calc(100vh - 60px)}aside{border-right:1px solid #e8e4ec;background:#fff;padding:16px;overflow:auto;height:calc(100vh - 60px)}section{padding:20px;overflow:auto;height:calc(100vh - 60px)}button,select,textarea,input{font:inherit}button{cursor:pointer}nav{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}nav button,.toolbar button{border:1px solid #ddd5e9;background:#fff;color:#4e3a69;border-radius:8px;padding:8px 12px}nav button.active{background:#7656b5;color:#fff}.list button{display:block;width:100%;border:1px solid #e8e4ec;background:#fff;border-radius:10px;text-align:left;padding:12px;margin:8px 0}.list button.selected{border-color:#7656b5;background:#f5f0ff}.list b,.list small{display:block}.list small,.meta{color:#777}.message{padding:12px;margin:12px 0;background:#fff;border-radius:10px;max-width:90%;white-space:pre-wrap;overflow-wrap:anywhere}.message.admin{margin-left:auto;background:#eee6fc}.message small{display:block;color:#777;margin-bottom:6px}.message button{display:block;margin-top:8px;border:1px solid #ddd5e9;background:#fff;border-radius:7px;padding:5px 8px}.message img{max-width:100%;max-height:360px;display:block;margin-top:8px}.toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:18px 0}.toolbar select,.toolbar input{padding:9px;border:1px solid #ddd5e9;border-radius:8px;background:#fff}.reply textarea,.note textarea{display:block;width:100%;min-height:80px;padding:10px;border:1px solid #ddd5e9;border-radius:9px;margin:8px 0}.primary{background:#7656b5!important;color:#fff!important;border:0!important;padding:10px 17px!important;border-radius:9px}.danger{color:#ad2637!important}#notice{color:#9b2638;margin:8px 0}h2{margin:0 0 8px}@media(max-width:760px){main{display:block}aside{height:auto;max-height:42vh;border-right:0;border-bottom:1px solid #ddd}section{height:auto;min-height:50vh}}
[hidden]{display:none!important}header{justify-content:space-between}#login{max-width:440px;margin:10vh auto;background:#fff;padding:24px;border-radius:14px;box-shadow:0 4px 24px #0000000d}#login input{width:100%;padding:12px;border:1px solid #ddd5e9;border-radius:9px;margin:8px 0 14px}#login-notice{color:#9b2638;margin:8px 0}
</style></head><body><header>EPhone · 反馈管理 <button id="logout" hidden>退出</button></header><div id="login"><h2>管理员登录</h2><p class="meta">输入只保存在本次浏览器标签页中的管理密钥。</p><form id="login-form"><label>管理密钥<input name="token" type="password" autocomplete="off" pattern="[0-9a-fA-F]{64}" required></label><button class="primary">进入管理页</button></form><div id="login-notice" role="status"></div></div><main hidden><aside><nav><button data-kind="all" class="active">全部</button><button data-kind="private">匿名对话</button><button data-kind="public">公开反馈</button><button id="refresh">刷新</button></nav><div class="toolbar"><input id="search" placeholder="搜索标题或编号" aria-label="搜索反馈"><select id="filter" aria-label="状态筛选"><option value="all">全部状态</option><option value="needs_reply">待回复</option><option value="pending">待审核</option><option value="visible">已公开</option><option value="closed">已关闭</option></select></div><div id="notice" role="status"></div><div id="list" class="list">正在加载…</div><button id="more" hidden>加载更早反馈</button></aside><section id="detail"><p class="meta">选择一条反馈查看并回复。</p></section></main>
<script>
(function(){
var all=[],kind='all',selected=null,nextCursor=null,token='';
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function date(v){return new Date(v).toLocaleString('zh-CN')}
function notice(v){document.getElementById('notice').textContent=v||''}
function lock(){token='';sessionStorage.removeItem('ephone_feedback_admin_token');document.getElementById('login').hidden=false;document.querySelector('main').hidden=true;document.getElementById('logout').hidden=true}
async function api(path,options){var opts=Object.assign({cache:'no-store'},options||{});var headers=new Headers(opts.headers||{});headers.set('Authorization','Bearer '+token);opts.headers=headers;var r=await fetch('/api'+path,opts);var data=await r.json().catch(function(){return {}});if(r.status===401)lock();if(!r.ok)throw Error(data.error||'请求失败');return data}
async function signIn(value){token=value.trim().toLowerCase();await api('/session');sessionStorage.setItem('ephone_feedback_admin_token',token);document.getElementById('login').hidden=true;document.querySelector('main').hidden=false;document.getElementById('logout').hidden=false;document.getElementById('login-notice').textContent='';await reload()}
function list(){var el=document.getElementById('list');var filter=document.getElementById('filter').value;var query=document.getElementById('search').value.trim().toLowerCase();var rows=all.filter(function(t){return (kind==='all'||t.kind===kind)&&(filter==='all'||(filter==='needs_reply'?t.last_visitor_at>t.last_admin_at:t.status===filter))&&(!query||t.title.toLowerCase().includes(query)||t.id.includes(query))});el.innerHTML=rows.length?rows.map(function(t){return '<button data-id="'+t.id+'" class="'+(selected===t.id?'selected':'')+'"><b>'+(t.last_visitor_at>t.last_admin_at?'● ':'')+esc(t.title)+'</b><small>'+(t.kind==='private'?'匿名':'公开')+' · '+esc(t.category)+' · '+esc(t.status)+' · '+date(t.updated_at)+'</small></button>'}).join(''):'暂无匹配反馈';document.getElementById('more').hidden=!nextCursor}
async function loadPage(reset){try{notice('');var data=await api('/threads'+(!reset&&nextCursor?'?before='+encodeURIComponent(nextCursor):''));all=reset?data.threads:all.concat(data.threads);nextCursor=data.nextCursor;list();if(reset&&selected&&all.some(function(t){return t.id===selected}))await detail(selected)}catch(e){notice(e.message)}}
async function reload(){return loadPage(true)}
async function detail(id){try{selected=id;list();var data=await api('/threads/'+id);var t=data.thread;var options=t.kind==='public'?['pending','visible','hidden','closed']:['open','closed'];var el=document.getElementById('detail');el.innerHTML='<h2>'+esc(t.title)+'</h2><div class="meta">'+(t.kind==='private'?'匿名对话':'公开反馈')+' · '+esc(t.category)+' · '+esc(t.nickname||'匿名用户')+' · '+date(t.created_at)+'</div><div class="toolbar"><label>状态 <select id="thread-status">'+options.map(function(v){return '<option value="'+v+'" '+(v===t.status?'selected':'')+'>'+v+'</option>'}).join('')+'</select></label><button id="save-status">保存状态</button><button id="delete-thread" class="danger">删除整段对话</button></div><div class="note"><label>内部备注<textarea id="thread-note" maxlength="1000"></textarea></label><button id="save-note">保存备注</button></div><div id="messages">'+data.messages.map(function(m){return '<article class="message '+(m.sender==='admin'?'admin':'visitor')+'"><small>'+(m.sender==='admin'?'我':'用户')+' · '+date(m.created_at)+'</small>'+esc(m.body)+(m.attachment_key?'<button data-image="'+m.attachment_key+'">查看截图</button>':'')+'</article>'}).join('')+'</div><form id="reply" class="reply"><label>回复<textarea name="body" maxlength="5000" required></textarea></label><button class="primary">发送回复</button></form>';
el.querySelector('#thread-note').value=t.note||'';
el.querySelector('#save-status').onclick=async function(){try{await api('/threads/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:el.querySelector('#thread-status').value})});await reload()}catch(e){notice(e.message)}};
el.querySelector('#save-note').onclick=async function(){try{await api('/threads/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({note:el.querySelector('#thread-note').value})});notice('备注已保存')}catch(e){notice(e.message)}};
el.querySelector('#delete-thread').onclick=async function(){if(!confirm('确定永久删除这段对话及截图吗？'))return;try{await api('/threads/'+id,{method:'DELETE'});selected=null;el.innerHTML='<p>已删除。</p>';await reload()}catch(e){notice(e.message)}};
el.querySelector('#reply').onsubmit=async function(ev){ev.preventDefault();var body=el.querySelector('[name=body]').value.trim();if(!body)return;try{await api('/threads/'+id+'/reply',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body:body})});await reload()}catch(e){notice(e.message)}};
el.querySelectorAll('[data-image]').forEach(function(button){button.onclick=async function(){try{var r=await fetch('/api/attachments/'+button.dataset.image,{headers:{Authorization:'Bearer '+token},cache:'no-store'});if(!r.ok)throw Error('截图加载失败');var url=URL.createObjectURL(await r.blob());var img=new Image();img.src=url;img.alt='反馈截图';img.onload=function(){URL.revokeObjectURL(url)};button.replaceWith(img)}catch(e){notice(e.message)}}});
}catch(e){notice(e.message)}}
document.getElementById('list').onclick=function(ev){var b=ev.target.closest('[data-id]');if(b)detail(b.dataset.id)};
document.querySelectorAll('[data-kind]').forEach(function(b){b.onclick=function(){kind=b.dataset.kind;document.querySelectorAll('[data-kind]').forEach(function(x){x.classList.toggle('active',x===b)});list()}});
document.getElementById('refresh').onclick=reload;document.getElementById('more').onclick=function(){loadPage(false)};document.getElementById('search').oninput=list;document.getElementById('filter').onchange=list;
document.getElementById('login-form').onsubmit=async function(ev){ev.preventDefault();try{await signIn(ev.target.elements.token.value)}catch(e){document.getElementById('login-notice').textContent=e.message}};
document.getElementById('logout').onclick=lock;
var saved=sessionStorage.getItem('ephone_feedback_admin_token');if(saved)signIn(saved).catch(function(e){document.getElementById('login-notice').textContent=e.message});
})();
</script></body></html>`;
